version: '3.8'
services:
  db:
    image: docker.io/library/postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=password
    volumes:
      - .:/app/albums:Z
volumes:
  dbdata:
